version: '3'

services:
    frontend:
        build: ./frontend
        restart: always
        ports:
          - '3000:3000'
        volumes:
          - /app/node_modules # Docerfile create thise forder --npm install and not destroy next step
          - ./frontend:/app
    api:
        build: ./api
        restart: always
        ports:
          - '5555:5000'
        depends_on:
          - mysql
        volumes:
          - /app/node_modules # Docerfile create thise forder --npm install and not destroy next step
          - ./api:/app
#         environment:
#          MYSQL_HOST: mysql
#          MYSQL_PORT: '3306'
#          MYSQL_USER: root
#          MYSQL_ROOT_PASSWORD: password
#          MYSQL_DATABASE: time_db
    mysql:
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: time_db
        volumes:
          - mysql_data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
          - '8080:8080'

volumes:
    mysql_data:
