version: '3'

services:
    frontend:
        image: jobmasalex/time-app-frontend-dev
        restart: always
        ports:
          - '3000:3000'

    api:
        image: jobmasalex/time-app-api-dev
        restart: always
        ports:
          - '5555:5000'
        depends_on:
          - mysql

    mysql:
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: time_db
        volumes:
          - mysql_data_pub:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
          - '8080:8080'

volumes:
    mysql_data_pub:
